name: safezone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^5.0.2
  google_fonts: ^6.3.0
  google_maps_flutter: ^2.9.0
  dio: ^5.7.0
  flutter_polyline_points: ^2.0.0
  url_launcher: ^6.3.0
  http: ^1.5.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  logger: ^2.0.2
  share_plus: ^11.1.0
  image_picker: ^1.0.7
  permission_handler: ^12.0.1    
  another_telephony: ^0.4.1
  firebase_core: 2.32.0
  firebase_messaging: ^14.7.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.jpg
    - assets/icon/
    - flutter.env